services:
  portfolio_app:
    container_name: portfolio
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: unless-stopped
    expose:
      - 4321

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    depends_on:
      - portfolio_app
    ports:
      - 4321:4321
    environment:
      - NGINX_PORT=4321
    command: ["/bin/sh", "-c", "envsubst '$$NGINX_PORT' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    build:
      context: .
      dockerfile: nginx.Dockerfile
