
services:
  portfolio_app:
    container_name: portfolio
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - cloudflare_default
    expose:
      - 4321

networks:
  cloudflare_default:
    external: true
