# THIS IS FOR LOCAL AND TESTING PURPOSES ONLY
services:
  portfolio:
    image: ghcr.io/ismola/personal-portfolio:master
    container_name: portfolio
    ports:
      - 4321:4321
    restart: unless-stopped