services:
  nginx:
    build:
      context: .
    container_name: portfolio_nginx
    ports:
      - 3000:4321
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
