services:
  portfolio_app:
    container_name: portfolio_app
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - cloudflare_default
    expose:
      - 4321
  portfolio:
    image: caddy:alpine
    container_name: portfolio
    depends_on:
      - portfolio_app
    ports:
      - "4321:4321"
    volumes:
      - ./Caddyfile:/Caddyfile:ro
    environment:
      - CADDYFILE_PATH=/Caddyfile
    command: caddy run --config /Caddyfile --adapter caddyfile
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
