services:
  portfolio:
    build:
      context: .
    container_name: portfolio
    ports:
      - 4321:4321
    networks:
      - cloudflare_default
    restart: unless-stopped

networks:
  cloudflare_default:
    external: true
