services:
  portfolio_app:
    container_name: portfolio_app
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - cloudflare_default
    expose:
      - 4321
  portfolio:
    image: caddy:alpine
    container_name: portfolio
    depends_on:
      - portfolio_app
    ports:
      - "4321:4321"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
